# Outlook 365
pacman::p_load(Microsoft365R, blastula, dplyr, stringr, DT, flextable, glue)

# Recupera los mensajes de interés
alumnos <- read.csv("../../posts/00-Bienvenida/Lista-de-alumnos-2026.csv")
outlb <- get_business_outlook()


bl_body <- "## Hello!
This is an email message that was generated by the **blastula** package. 
We can use _italics_ formatting and [links](https://example.com) with the `md()` function.

* Bullet points
* are also supported

Cheers,
The R user"

bl_em <- compose_email(
  body = md(bl_body),
  footer = md("Sent via Microsoft365R")
)


em <- outlb$create_email(
  bl_em, 
  subject = "Markdown Email from R-3", 
  to = "equihuam@gmail.com"
)

em$send()
