<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Miguel Equihua">

<title>Modelos de Efectos Mixtos – Curso de Estadística (Inecol 2025)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/bar-chart.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-1b3e43c72e8be34557c75123b0b69e0d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-1b3e43c72e8be34557c75123b0b69e0d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-1b3e43c72e8be34557c75123b0b69e0d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-cc0c66d3a9e636430becf437bf8ba876.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-14d41249204da2b1aa42c37d647f6e65.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-cc0c66d3a9e636430becf437bf8ba876.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Curso de Estadística (Inecol 2025)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-algo-más" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Algo más</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-algo-más">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">Acerca de</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../presentaciones.html">
 <span class="dropdown-text">M3-Presentaciones</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ejercicios.html">
 <span class="dropdown-text">M3-ejercicios</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/equihuam/M3-2024_causalidad"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Modelos de Efectos Mixtos</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">clase</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Miguel Equihua </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">5 de febrero de 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<p><img src="images/arboles.jpeg" class="img-fluid" width="500"></p>
<section id="modelos-lineales-de-efectos-mixtos" class="level1">
<h1>Modelos Lineales de efectos mixtos</h1>
<section id="ejemplo-de-rieles" class="level2">
<h2 class="anchored" data-anchor-id="ejemplo-de-rieles">Ejemplo de rieles</h2>
<div class="callout callout-style-default callout-note callout-titled" title="Calidad de rieles de ferrocarril">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Calidad de rieles de ferrocarril
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Uno de los principales problemas que enfrentan los ferrocarriles es la falla en las vías. Los defectos en los raíles, como parte básica de la vía, pueden provocar accidentes graves. La inspección de los rieles es crítica, considerando el enorme tráfico que soportan actualmente, la mayor velocidad y las cargas más pesadas. La inspección visual sólo puede detectar defectos superficiales y, a veces, signos evidentes de problemas internos, la <em>defectoscopia ultrasónica</em> desempeña un papel insustituible en la inspección de los rieles durante su funcionamiento.</p>
<p><img src="images/ultrasonic-railway-rail-testing-01.jpg" class="img-fluid" data-wdth="60%"></p>
<p><a href="https://faculty.ksu.edu.sa/sites/default/files/probability_and_statistics_for_engineering_and_the_sciences.pdf">Este ejemplo se explica en este libro</a>.</p>
</div>
</div>
</div>
<p>El estudio de las fuerzas y tensiones no destructivas en los materiales proporciona información importante para un diseño de ingeniería eficaz. El artículo <em>Zero-Force Travel-Time Parameters for Ultrasonic Head-Waves in Railroad</em> (Materials Evaluation, 1985: 854-858) reporta un estudio del <strong>tiempo de tránsito</strong> de un <em>cierto tipo de onda</em> que se obtiene al someter rieles de ferrocarril a esfuerzos de tensión longitudinal. Se realizaron tres mediciones en cada uno de seis rieles seleccionados aleatoriamente de una población más amplia de ellos. Los investigadores buscaban caracterizar la variación en el tiempo de viaje como referencia para describir la <em>variabilidad</em> <strong><em>típica</em></strong> <em>entre los rieles</em> que estaban adquiriendo y usando. Los ingenieros se interesaban en precisar la variabilidad atribuible al ejercicio de realizar las mediciones en un mismo riel y la variailidad que expresan los distintos rieles. Los datos son valores en nanosegundos, resultado de restar 36.1 <span class="math inline">\(\mu s\)</span> a cada observación.</p>
<p>Este ejemplo es un caso simple de efectos aleatorios. En resumen, seis rieles fueron tomados al azar y sometidos a prueba tres veces cada uno mediante la medición del tiempo que le toma a cierto tipo de ondas ultrasónicas viajar a lo largo del riel. La Única <em>condición experimental</em> que cambia entre observaciones es el riel.</p>
<p>Claramente el estudio tiene un solo criterio de clasificación, como posible condición de contraste. La intención del estudio fue la determinación de:</p>
<ol type="1">
<li><strong>Tiempo de tránsito “típico”</strong> de un riel (tiempo esperado de tránsito)</li>
<li><em>Variación</em> en el tiempo de tránsito promedio <em>entre los rieles</em> (variabilidad entre rieles)</li>
<li><em>Variación al medir</em> el tiempo observado de tránsito <em>en un mismo riel</em> (variabilidad dentro de rieles)</li>
</ol>
<p><span class="math display">\[
y_{ij} = \mu + \beta_{1} R_{i} + \varepsilon_{i(j)}
\]</span></p>
<p>Utilizaremos la biblioteca <code>nlme</code> (<em>Linear and Nonlinear Mixed Effects Models</em>, de tipo Gausiano o normal) para ajustar los modelos de <em>efectos mixtos</em> y aprovecharé para que veamos dos bibliotecas de graficación de <em>calidad publicación</em>: <code>lattice</code> y <code>ggplot2</code> .</p>
<p><strong>Lattice contiene estas opciones:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>tipo de gráfica</th>
<th>descripción</th>
<th>ejemplo de fórmula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>barchart</td>
<td>bar chart</td>
<td>x~A or A~x</td>
</tr>
<tr class="even">
<td>bwplot</td>
<td>boxplot</td>
<td>x~A or A~x</td>
</tr>
<tr class="odd">
<td>cloud</td>
<td>3D scatterplot</td>
<td>z~x*y|A</td>
</tr>
<tr class="even">
<td>contourplot</td>
<td>3D contour plot</td>
<td>z~x*y</td>
</tr>
<tr class="odd">
<td>densityplot</td>
<td>kernal density plot</td>
<td>~x|A*B</td>
</tr>
<tr class="even">
<td>dotplot</td>
<td>dotplot</td>
<td>~x|A</td>
</tr>
<tr class="odd">
<td>histogram</td>
<td>histogram</td>
<td>~x</td>
</tr>
<tr class="even">
<td>levelplot</td>
<td>3D level plot</td>
<td>z~y*x</td>
</tr>
<tr class="odd">
<td>parallel</td>
<td>parallel coordinates plot</td>
<td>data frame</td>
</tr>
<tr class="even">
<td>splom</td>
<td>scatterplot matrix</td>
<td>data frame</td>
</tr>
<tr class="odd">
<td>stripplot</td>
<td>strip plots</td>
<td>A~x or x~A</td>
</tr>
<tr class="even">
<td>xyplot</td>
<td>scatterplot</td>
<td>y~x|A</td>
</tr>
<tr class="odd">
<td>wireframe</td>
<td>3D wireframe graph</td>
<td>z~y*x</td>
</tr>
</tbody>
</table>
<p>Las gráficas con <code>lattice</code> tienen todo un entorno de soporte. Por ejemplo los aspectos que pueden ajustarse se pueden ver con <code>trellis.par.get()</code> y se ajustan con <code>trellis.par.set()</code>. Se trata de una aproximación a la <strong>visualización de datos</strong> muy interesante que se desarrolló en la época en la que los lenguajes de programación <strong>S</strong> y más adelante <strong>R</strong>, estaban apareciendo. Quizás popr eso encontramos algo de <code>lattice</code> contruido dentro de <code>nlme</code>.</p>
<p>Actualmente, resulta quizás más práctico el enfoque que ha desarrollado <code>ggplot2</code>, basada en una <a href="https://link.springer.com/book/10.1007/978-0-387-98141-3">semántica de graficación que Hadley Wickham explica originamente en su libro publicado en 2009</a>. Actualmente Hadley trabaja con otros dos coautores (Danielle Navarro y Thomas Lin Pedersen) en al 3ra. edición, lo hacen como un <a href="https://ggplot2-book.org/"><em>preprint</em> que pueden encontrar aquí</a>. La gran influencia de este planteamiento a la producción de gráficas de datos ha dado lugar a muchas ideas y recursos de ayuda que fácilmente se pueden encontrar en <em>la Web</em></p>
<p>los datos con los que trabajaremos en esta sesión están en la tabla <code>Rail</code> de la biblioteca <em>nlme</em>. Para acomodarlos a mis propósitos los copie a mi espacio de trabajo y los guardé en una variable con un nombre de mi gusto. Los datos de los rieles están ordenados según fueron ensayados.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>rieles <span class="ot">&lt;-</span> Rail</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(rieles) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"riel"</span>, <span class="st">"viaje"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rieles)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'nffGroupedData', 'nfGroupedData', 'groupedData' and 'data.frame':  18 obs. of  2 variables:
 $ riel : Ord.factor w/ 6 levels "2"&lt;"5"&lt;"1"&lt;"6"&lt;..: 3 3 3 1 1 1 5 5 5 6 ...
 $ viaje: num  55 53 54 26 37 32 78 91 85 92 ...
 - attr(*, "labels")=List of 1
  ..$ y: chr "Zero-force travel time"
 - attr(*, "units")=List of 1
  ..$ y: chr "(nanoseconds)"
 - attr(*, "formula")=Class 'formula'  language travel ~ 1 | Rail
  .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
 - attr(*, "order.groups")= logi TRUE</code></pre>
</div>
</div>
<p>La tabla <code>rieles</code> fue creada como una <strong>estructura agrupada</strong> con la función <code>groupeData</code> de la biblioteca <code>nlme</code>. Veremos más adelante como usar esta función. Esta función agrega <em>metadatos</em> a la tabla. Si interesa hacer cambios a los <em>metadatos</em> de la tabla agrupada hay que usar la función <code>update</code> que ejemplificaré a continuación. Lo primero es explorar los atributos asignados.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(rieles)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$names
[1] "riel"  "viaje"

$class
[1] "nffGroupedData" "nfGroupedData"  "groupedData"    "data.frame"    

$row.names
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18"

$labels
$labels$y
[1] "Zero-force travel time"


$units
$units$y
[1] "(nanoseconds)"


$formula
travel ~ 1 | Rail

$order.groups
[1] TRUE</code></pre>
</div>
</div>
<p>Ahora cambiemos estos atributos para que todo esté expresado en español y de paso corregir la fórmula, que tal como está, pierde la referencia adecuada a las variables que contiene la tabla, pues yo cambié los nombres de las variables.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>rieles  <span class="ot">&lt;-</span> <span class="fu">update</span>(rieles, <span class="at">formula =</span> viaje <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> riel, <span class="at">FUN =</span> mean,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels =</span> <span class="fu">list</span>(<span class="at">y =</span> <span class="st">"Tiempo de viaje con fuerza cero"</span>),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">units =</span> <span class="fu">list</span>(<span class="at">y =</span> <span class="st">"(nano segundos)"</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Encontré un detallito raro de atributos que se quedan con basura. </span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Aunque no parecen producir ningún problema, esta es una manera de limpiarla.</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(<span class="fu">attributes</span>(rieles)<span class="sc">$</span>formula)<span class="sc">$</span><span class="st">".Environment"</span> <span class="ot">&lt;-</span> <span class="fu">environment</span>()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">environment</span>(<span class="fu">attributes</span>(rieles)<span class="sc">$</span>FUN) <span class="ot">&lt;-</span> <span class="fu">environment</span>()</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(rieles)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$names
[1] "riel"  "viaje"

$row.names
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18"

$class
[1] "nffGroupedData" "nfGroupedData"  "groupedData"    "data.frame"    

$formula
viaje ~ 1 | riel

$labels
$labels$y
[1] "Tiempo de viaje con fuerza cero"


$units
$units$y
[1] "(nano segundos)"


$FUN
function (x, ...) 
UseMethod("mean")

$order.groups
[1] TRUE</code></pre>
</div>
</div>
<p>A esta tabla se le ha aplicado la función <code>groupedData</code> con la fórmula:</p>
<p>viaje ~ 1| riel</p>
<p>Esta estrategia permite darle mantenimiento a los metadatos, que incluyen indicaciones sobre el agrupamiento de los datos en la tablas. Para aprovechar esta estructura podemos usar funciones especiales, por cierto, dentro del paquete <code>nmle</code>, la función <code>plo</code> ha sido diseñada para usar opciones de graficación de <em>lattice</em>, puedes averiguar un poco más al respecto con <code>help(plot.nmGroupedData)</code>:</p>
<ul>
<li><code>gapply</code> - aplica funciones por grupos</li>
<li><code>gsummary</code> - calcula los resúmenes de datos por grupos</li>
</ul>
<p>Por lo pronto veamos los datos, con la función de graficación de <em>lattice</em> <code>stripplot</code>, que toma el factor <em>riel</em>, por lo tanto se trata de <em>renglones</em> cualitativos sobre los que se grafican los datos de <em>velocidad de viaje</em>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width=</span><span class="dv">10</span>, <span class="at">repr.plot.height=</span><span class="dv">6</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stripplot</span>(rieles<span class="sc">$</span>riel <span class="sc">~</span> rieles<span class="sc">$</span>viaje, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">cex =</span> <span class="fl">1.25</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="fu">list</span>(<span class="at">label =</span> <span class="st">"Análisis de integridad estructural de rieles"</span>, <span class="at">cex =</span><span class="dv">2</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="fu">list</span>(<span class="at">label =</span> <span class="st">"tiempo de viaje (ns)"</span>, <span class="at">cex =</span> <span class="dv">2</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylab =</span>  <span class="fu">list</span>(<span class="at">label =</span> <span class="st">"riel"</span>, <span class="at">cex =</span> <span class="dv">2</span>), </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">scales =</span> <span class="fu">list</span>(<span class="at">tck =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">0</span>), <span class="at">x =</span> <span class="fu">list</span>(<span class="at">cex =</span> <span class="dv">2</span>), <span class="at">y =</span> <span class="fu">list</span>(<span class="at">cex =</span> <span class="dv">2</span>)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><span style="color:GoldenRod">¿Cómo se ven estos datos? ¿qué piensas que habría que hacer?</span></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rieles, <span class="fu">aes</span>(<span class="at">x =</span> viaje, <span class="at">y =</span> riel, <span class="at">group =</span> riel)) <span class="sc">+</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">19</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Análisis de integridad estructural de rieles"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"tiempo de viaje (ns)"</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"riel"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">26</span>), </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">0</span>, <span class="at">hjust=</span><span class="dv">1</span>)) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gsummary</span>(rieles)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  riel    viaje
2    2 31.66667
5    5 50.00000
1    1 54.00000
6    6 82.66667
3    3 84.66667
4    4 96.00000</code></pre>
</div>
</div>
<p>¿Cómo se asigna la estructura de agrupación a una tabla de datos? Como dije al principio, se puede usar la función groupedData de la biblioteca <em>nlme</em>. Hagamos un ahora un ensayo de este proceso.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>rieles.sg <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(rieles)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Estructura de la tabla <strong>sin</strong> información de agrupamiento:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rieles.sg) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   18 obs. of  2 variables:
 $ riel : Ord.factor w/ 6 levels "2"&lt;"5"&lt;"1"&lt;"6"&lt;..: 3 3 3 1 1 1 5 5 5 6 ...
 $ viaje: num  55 53 54 26 37 32 78 91 85 92 ...</code></pre>
</div>
</div>
<p>Los atributos quue contiene este objeto son estos:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(rieles.sg)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$names
[1] "riel"  "viaje"

$row.names
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18"

$class
[1] "data.frame"</code></pre>
</div>
</div>
<p>Tomo los datos sin agrupamiento y proporciono los <em>metadatos</em> que definen la <strong>estructura de agrupamiento</strong> que caracterizan a la tabla :</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rieles.g <span class="ot">&lt;-</span> <span class="fu">groupedData</span> (viaje <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> riel, <span class="at">data =</span> rieles.sg, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FUN =</span> mean,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">units =</span> <span class="fu">list</span>( <span class="at">x =</span> <span class="st">"(ns)"</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">"riel"</span>, </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">y =</span> <span class="st">"tiempo de tránsito de fuerza cero"</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rieles.g)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'nffGroupedData', 'nfGroupedData', 'groupedData' and 'data.frame':  18 obs. of  2 variables:
 $ riel : Ord.factor w/ 6 levels "2"&lt;"5"&lt;"1"&lt;"6"&lt;..: 3 3 3 1 1 1 5 5 5 6 ...
 $ viaje: num  55 53 54 26 37 32 78 91 85 92 ...
 - attr(*, "formula")=Class 'formula'  language viaje ~ 1 | riel
  .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
 - attr(*, "labels")=List of 2
  ..$ x: chr "riel"
  ..$ y: chr "tiempo de tránsito de fuerza cero"
 - attr(*, "units")=List of 1
  ..$ x: chr "(ns)"
 - attr(*, "FUN")=function (x, ...)  
 - attr(*, "order.groups")= logi TRUE</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">sg=</span>rieles.sg, <span class="at">g=</span>rieles.g)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   sg.riel sg.viaje g.riel g.viaje
1        1       55      1      55
2        1       53      1      53
3        1       54      1      54
4        2       26      2      26
5        2       37      2      37
6        2       32      2      32
7        3       78      3      78
8        3       91      3      91
9        3       85      3      85
10       4       92      4      92
11       4      100      4     100
12       4       96      4      96
13       5       49      5      49
14       5       51      5      51
15       5       50      5      50
16       6       80      6      80
17       6       85      6      85
18       6       83      6      83</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gsummary</span>(rieles.sg)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    riel viaje
26     2    26
32     2    32
37     2    37
49     5    49
50     5    50
51     5    51
53     1    53
54     1    54
55     1    55
78     3    78
80     6    80
83     6    83
85     3    85
91     3    91
92     4    92
96     4    96
100    4   100</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gsummary</span>(rieles.g)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  riel    viaje
2    2 31.66667
5    5 50.00000
1    1 54.00000
6    6 82.66667
3    3 84.66667
4    4 96.00000</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rieles.g, <span class="fu">aes</span>(<span class="at">x =</span> viaje, <span class="at">y =</span> riel, <span class="at">group =</span> riel)) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">19</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Análisis de integridad estructural de rieles (rieles.g)"</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"tiempo de viaje (ns)"</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"riel"</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">26</span>), </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">0</span>, <span class="at">hjust=</span><span class="dv">1</span>)) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como hemos visto, cambiar los metadatos de la tabla se hace con la función <code>update()</code>.</p>
<p>Como una demostración simple de esto, le cambiaré la etiqueta asociada a la variable de respuesta en la estructura de agrupamiento. Con esto.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>rieles.g1 <span class="ot">&lt;-</span> <span class="fu">update</span>(rieles.g, <span class="at">labels =</span> <span class="fu">list</span>(<span class="at">y=</span><span class="st">"tiempo (ns)"</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rieles.g1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Primera posibilidad de análisis. Modelo lineal simple. Es una elección natural en este caso, pues estima la media general. Hay que recordar seleccionar contrastes de tipo “tratamiento” aun para factores ordenados.</p>
<p><span style="color:GoldenRod">¿Cómo representamos al riel en el modelo?</span></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span> ()<span class="sc">$</span>contrasts</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        unordered           ordered 
"contr.treatment"      "contr.poly" </code></pre>
</div>
</div>
<p>Empecemos por construir el modelo nulo. <span style="color:GoldenRod">¿qué resultados nos ofrece este modelo?</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>rieles.m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(viaje <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span>rieles.g)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rieles.m1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = viaje ~ 1, data = rieles.g)

Residuals:
   Min     1Q Median     3Q    Max 
-40.50 -16.25   0.00  18.50  33.50 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   66.500      5.573   11.93  1.1e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 23.65 on 17 degrees of freedom</code></pre>
</div>
</div>
<p>Así, tengo una estimación del tiempo promedio de tránsito de: 66.5. El error estándar que estimo es: 5.573</p>
<p><span style="color:GoldenRod">¿cómo quedan los residuos de este modelo?</span></p>
<p>El gráfico de <em>cajas y bigotes</em> o <em>cajas y alambres</em> es interesante para explorar lo que está pasando con los rieles. La versión que produce la función <code>bwplot()</code> de la biblioteca <em>lattice</em> es un buen recurso.</p>
<p><span style="color:GoldenRod">¿Qué piensas de esta gráfica? ¿Te gusta lo que ves?</span></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(rieles.g<span class="sc">$</span>riel <span class="sc">~</span> <span class="fu">resid</span>(rieles.m1))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rieles.g, <span class="fu">aes</span>(<span class="at">x =</span> viaje, <span class="at">y =</span> riel, <span class="at">group =</span> riel)) <span class="sc">+</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">stat_boxplot</span>(<span class="at">geom=</span><span class="st">'errorbar'</span>, <span class="at">linetype=</span><span class="dv">2</span>, <span class="at">width=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_boxplot</span>(<span class="at">shape =</span> <span class="dv">19</span>, <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Análisis de integridad estructural de rieles (rieles.g)"</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">xlab</span>(<span class="at">label =</span> <span class="st">"tiempo de viaje (ns)"</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">ylab</span>(<span class="at">label =</span> <span class="st">"riel"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">26</span>), </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">0</span>, <span class="at">hjust=</span><span class="dv">1</span>)) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Al ignorar el efecto de los rieles, dentro de los que repito la prueba para obtener las medidas de interés se produce un defecto que se ve claramente en esta gráfica de residuos.</p>
<p>Los residuos de cada riel tienen todos el mismo signo. Es decir se mantiene un efecto sistemático importante en ellos.</p>
<p><span style="color:GoldenRod">Te parecería buena idea agregar el término que representa al riel para resolver este problema?</span></p>
<p><span style="color:GoldenRod">¿Es fijo o aleatorio?</span></p>
<p>Este nuevo modelo permite que cada riel sea representado por una media diferente. Suponiendo efectos fijos, la estimación del parámetro de interés es esta.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>rieles.m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(viaje <span class="sc">~</span> riel <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span>rieles.g)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>rieles.m2</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = viaje ~ riel - 1, data = rieles.g)

Coefficients:
riel2  riel5  riel1  riel6  riel3  riel4  
31.67  50.00  54.00  82.67  84.67  96.00  </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(rieles.m2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: viaje
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
riel       6  88911 14818.5  916.61 2.971e-15 ***
Residuals 12    194    16.2                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rieles.m2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = viaje ~ riel - 1, data = rieles.g)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.6667 -1.0000  0.1667  1.0000  6.3333 

Coefficients:
      Estimate Std. Error t value Pr(&gt;|t|)    
riel2   31.667      2.321   13.64 1.15e-08 ***
riel5   50.000      2.321   21.54 5.86e-11 ***
riel1   54.000      2.321   23.26 2.37e-11 ***
riel6   82.667      2.321   35.61 1.54e-13 ***
riel3   84.667      2.321   36.47 1.16e-13 ***
riel4   96.000      2.321   41.35 2.59e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.021 on 12 degrees of freedom
Multiple R-squared:  0.9978,    Adjusted R-squared:  0.9967 
F-statistic: 916.6 on 6 and 12 DF,  p-value: 2.971e-15</code></pre>
</div>
</div>
<p><span style="color:GoldenRod">¿interpretación de este nuevo resultado?</span></p>
<p>……….. <span style="color:GoldenRod">¿y los residuos? ¿cómo se ven ahora?</span></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(rieles.g<span class="sc">$</span>riel <span class="sc">~</span> <span class="fu">resid</span>(rieles.m2))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>res.m2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">resid =</span> <span class="fu">resid</span>(rieles.m2), <span class="at">riel =</span> rieles.g<span class="sc">$</span>riel)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(res.m2, <span class="fu">aes</span>(<span class="at">x =</span> resid, <span class="at">y =</span> riel, <span class="at">group =</span> riel)) <span class="sc">+</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">stat_boxplot</span>(<span class="at">geom=</span><span class="st">'errorbar'</span>, <span class="at">linetype=</span><span class="dv">2</span>, <span class="at">width=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_boxplot</span>(<span class="at">shape =</span> <span class="dv">19</span>, <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"blue"</span>) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A pesar de que el modelo remueve los efectos sistemáticos asociados a las características particulares de los distintos rieles, no proporciona una representación satisfactoria del problema.</p>
<p><span style="color:GoldenRod">si los rieles fueran de efectos fijos ¿qué implicaría este modelo? ¿cuál sería una interpretación razonable del tratamiento <strong>riel</strong>?</span></p>
<p>Al suponer efectos fijos surge el problema de que se modelan de algún modo <em>variantes individuales</em> de los rieles que se usaron para realizar las pruebas. Desafortunadamente, tal clasificación no tiene ningún sentido en el contexto. Lo que interesa es estimar el tiempo de tránsito típico de cualquier riel en la <em>población de rieles</em> de la que se tomó la muestra.</p>
<p>Además, la misma falta de correspondencia conceptual entre el modelo y la estimación que interesa, hace que este nuevo modelo no proporcione una clara estimación de la variación (componente de varianza), entre rieles, que es otra de las preguntas centrales de este estudio. Otro problema de este modelo de efectos fijos es que el número de parámetros crece linealmente con el número de rieles que se usan para realizar la prueba, generando un comportamiento extraño en el modelo respecto de la pregunta.</p>
<section id="el-modelo-de-efectos-aleatorios-resuelves-estos-problemas." class="level4">
<h4 class="anchored" data-anchor-id="el-modelo-de-efectos-aleatorios-resuelves-estos-problemas.">El Modelo de efectos aleatorios ¿resuelves estos problemas?.</h4>
<p>En este enfoque se considera a los rieles como un efecto aleatorio sobre la media general. Hay principalmente dos métodos para ajustar este tipo de modelos el de máxima verosimilitud (ML) y el de máxima verosimilitud restringida (REML, default). La función que utilizaremos para el caso lineal es <code>lme()</code> que se usa de modo muy semejante a <code>lm()</code> y <code>glm()</code>. Sin embargo, nótese que ahora el modelo tiene dos grupos de fórmulas, una para describir los efectos fijos (opción <em>fixed</em>) y otra para describir los aleatorios (opción <em>random</em>). Esté último es siempre una fórmula que tiene sólo el lado derecho (no hay interés en predecir medias, ¿recuerdas?) y da cuenta de los efectos aleatorios y de la estructura de agrupamiento de los datos. Un agrupamiento se representa mediante el símbolo de barra vertical: <code>|</code>. Ahora, ajustemos un modelo de este tipo para obtener la estimación de <em>máxima verosimilitud restringida</em> para los rieles.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>rieles.m3 <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed =</span> viaje <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> riel, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> rieles.g)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>rieles.m3</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by REML
  Data: rieles.g 
  Log-restricted-likelihood: -61.0885
  Fixed: viaje ~ 1 
(Intercept) 
       66.5 

Random effects:
 Formula: ~1 | riel
        (Intercept) Residual
StdDev:    24.80547 4.020779

Number of Observations: 18
Number of Groups: 6 </code></pre>
</div>
</div>
</section>
</section>
<section id="ayúdame-a-comentar-estos-resultados-qué-te-llama-la-atención" class="level2 callou-caution" style="color:GoldenRod">
<h2 class="anchored" data-anchor-id="ayúdame-a-comentar-estos-resultados-qué-te-llama-la-atención">Ayúdame a comentar estos resultados ¿qué te llama la atención?</h2>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span> (rieles.m3)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by REML
  Data: rieles.g 
      AIC      BIC   logLik
  128.177 130.6766 -61.0885

Random effects:
 Formula: ~1 | riel
        (Intercept) Residual
StdDev:    24.80547 4.020779

Fixed effects:  viaje ~ 1 
            Value Std.Error DF  t-value p-value
(Intercept)  66.5  10.17104 12 6.538173       0

Standardized Within-Group Residuals:
        Min          Q1         Med          Q3         Max 
-1.61882658 -0.28217671  0.03569328  0.21955784  1.61437744 

Number of Observations: 18
Number of Groups: 6 </code></pre>
</div>
</div>
</section>
<p>El ajuste produce los estimadores que buscamos: 1. tiempo de tránsito típico = 66.5 2. Variabilidad entre rieles = 24.81 3. Variabilidad dentro de rieles = 4.02</p>
<p>En este caso los estimadores 1 y 3 son prácticamente idénticos a los obtenidos con el modelo lineal ordinario, pero esto no siempre es así. La coincidencia deriva de que la muestra está balanceada (mismo tamaño de muestra en cada riel). Además, ahora tengo un razonable estimador de la variación entre rieles (2).</p>
<p><span style="color:GoldenRod">¿Qué utilidad pueden tener estas estimaciones?</span></p>
<p>El resumen del ajuste muestra dos criterios nuevos para comparar y evaluar modelos. Estas medidas son resultado de la búsqueda de alternativas para valorar modelos que no se centre en el famoso valor de <em>p</em>.</p>
<ul>
<li>AIC - Criterio de información de Akaike = -2 * logVerosimilitud + 2 numParámetros</li>
<li>BIC - Criterio de información bayesiano = -2 * logVerosimilitud + numParámetros * log(N)</li>
</ul>
<p>Es bueno contar con ellos para comparar la calidad general de los modelos ajustados, pero no olviden que centrar nuestra atención en los intervalos de confianza es más informativo y potencialmente interesante.</p>
<p>En cualquier caso, “entre más pequeño el valor del criterio, mejor”, pero no olvides que más interesantes son los intervalos de confianza que obtengas.Finalmente, veamos los residuos</p>
<p><span style="color:GoldenRod">¿Cómo se ven?</span></p>
<p><span style="color:GoldenRod">¿Qué nos sugieren estos resultados?</span></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(rieles.g<span class="sc">$</span>riel <span class="sc">~</span> <span class="fu">resid</span>(rieles.m3))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Puedo obtener los estimadores de los coeficientes igual que en el caso <code>lm()</code> y <code>glm()</code> con <code>coef()</code>, pero además puedo obtener los coeficientes de los componentes aleatorios con <code>random.effects()</code> (forma breve: <code>ranef()</code>). ¿Que hay de los intervalos de confianza de los parámetros de efectos fijos estimados?.</p>
<p>Como he venido insistiendo, esta forma de mostrar resultados es cada vez más apreciada y es más conveniente que el enfoque de uso de valores de “<em>p</em>” en las publicaciones. La función <code>intervals()</code> supone un nivel de confianza del 95%, si no se le dice otra cosa.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(rieles.m3)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)
2    31.96909
5    50.14325
1    54.10852
6    82.52631
3    84.50894
4    95.74388</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(rieles.m3)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)
2   -34.53091
5   -16.35675
1   -12.39148
6    16.02631
3    18.00894
4    29.24388</code></pre>
</div>
</div>
<p><span style="color:GoldenRod">¿Qué piensas de estos estimadores de intervalos de confianza?</span></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intervals</span>(rieles.m3, <span class="fl">0.95</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Approximate 95% confidence intervals

 Fixed effects:
               lower est.    upper
(Intercept) 44.33921 66.5 88.66079

 Random Effects:
  Level: riel 
                   lower     est.    upper
sd((Intercept)) 13.27436 24.80547 46.35335

 Within-group standard error:
   lower     est.    upper 
2.695012 4.020779 5.998737 </code></pre>
</div>
</div>
<section id="el-modelo-de-glucógeno-en-ratas-revisitado" class="level2">
<h2 class="anchored" data-anchor-id="el-modelo-de-glucógeno-en-ratas-revisitado">El modelo de glucógeno en ratas revisitado</h2>
<p>Volvamos a ver el ejemplo GLEX38 (Crawley p.&nbsp;149) de Hígados de rata en el ejemplo presentado originalmente en Sokal &amp; Rohlf (1981). Te recuerdo que se trata de un experimento con un solo factor con tres tratamientos administrados a seis ratas, dos por tratamiento. El análisis se complica por el hecho de que, para el an?lisis, se tomaron tres muestras del hígado de cada rata y se hicieron dos determinaciones de contenido de glucógeno en cada muestra. Así, podríamos decir, un tanto derogativamente, que hay seis <strong>pseudoréplicas</strong> por rata para dar un total de 36 lecturas en total. Pero quizás en lugar de hablar en estos términos deberíamos simmplemente reconocer que lo que estamos haciendo es organizar un muestreao para obtener el dato de la variable de respuesta en el experimento, en lugar de hacer una “cosecha total”, que es la práctica ideal (pues evita introducir un fuente de “ruido” adicional).</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>ratas_g <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"hígados-rata.DAT"</span>, <span class="at">col.names=</span><span class="st">"glucogeno"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>ratas_g<span class="sc">$</span>tratamiento <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"t1"</span>,<span class="st">"t2"</span>,<span class="st">"t3"</span>),<span class="at">each=</span><span class="dv">12</span>))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>ratas_g<span class="sc">$</span>rata <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">paste</span>(<span class="st">"r"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">sep=</span><span class="st">""</span>), <span class="at">each=</span><span class="dv">6</span>))</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>ratas_g<span class="sc">$</span>muestraH <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"m1"</span>, <span class="st">"m2"</span>, <span class="st">"m3"</span>), <span class="at">times=</span><span class="dv">6</span>, <span class="at">each=</span><span class="dv">2</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Le doy estructura de grupos a la tabla</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>ratas_g <span class="ot">&lt;-</span> <span class="fu">groupedData</span>(glucogeno <span class="sc">~</span>  <span class="dv">1</span> <span class="sc">|</span> <span class="fu">ordered</span>(rata) <span class="sc">/</span> muestraH,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> ratas_g,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels=</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">"rata"</span>, <span class="at">y =</span> <span class="st">"contenido de glucógeno"</span> ),</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">FUN =</span> mean)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ratas_g)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'nmGroupedData', 'groupedData' and 'data.frame':    36 obs. of  4 variables:
 $ glucogeno  : int  131 130 131 125 136 142 150 148 140 143 ...
 $ tratamiento: Factor w/ 3 levels "t1","t2","t3": 1 1 1 1 1 1 1 1 1 1 ...
 $ rata       : Factor w/ 6 levels "r1","r2","r3",..: 1 1 1 1 1 1 2 2 2 2 ...
 $ muestraH   : Factor w/ 3 levels "m1","m2","m3": 1 1 2 2 3 3 1 1 2 2 ...
 - attr(*, "formula")=Class 'formula'  language glucogeno ~ 1 | ordered(rata)/muestraH
  .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
 - attr(*, "formulaList")=List of 2
  ..$ ordered(rata):Class 'formula'  language ~ordered(rata)
  .. .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
  ..$ muestraH     :Class 'formula'  language ~muestraH
  .. .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
 - attr(*, "labels")=List of 2
  ..$ x: chr "rata"
  ..$ y: chr "contenido de glucógeno"
 - attr(*, "order.groups")=List of 2
  ..$ ordered(rata): logi TRUE
  ..$ muestraH     : logi TRUE
 - attr(*, "FUN")=function (x, ...)  </code></pre>
</div>
</div>
<section id="exploración-de-los-datos" class="level3">
<h3 class="anchored" data-anchor-id="exploración-de-los-datos">Exploración de los datos</h3>
<p>Aprovechando las opciones de estructura de grupos puedo obtener resumenes exploratorios de manera muy simple.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">promedio =</span> <span class="fu">tapply</span> (ratas_g<span class="sc">$</span>glucogeno, ratas_g<span class="sc">$</span>rata, <span class="cf">function</span>(x) <span class="fu">round</span>(<span class="fu">mean</span>(x), <span class="dv">2</span>)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   promedio
r1   132.50
r2   148.50
r3   149.67
r4   152.33
r5   134.33
r6   136.00</code></pre>
</div>
</div>
<p>Graficación de los datos aprovechando la estructura agrupada que hemos adoptado.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ratas_g, <span class="at">inner =</span>  <span class="sc">~</span> tratamiento, <span class="at">displayLeve=</span><span class="dv">2</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(glucogeno <span class="sc">~</span> tratamiento, <span class="at">boxmeans=</span>T, <span class="at">data=</span>ratas_g, </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">boxcol=</span><span class="dv">14</span>, <span class="at">xlab =</span> <span class="st">"Tratamiento"</span>, <span class="at">ylab =</span> <span class="st">"Contenido de glucógeno"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="modelación" class="level3">
<h3 class="anchored" data-anchor-id="modelación">Modelación</h3>
<p>Veamos el enfoque con un modelo lineal de efectos mixtos.</p>
</section>
</section>
<section id="cual-es-la-estructura-fija-me-puedes-decir-cuál-es-la-ecuación-correspondiente" class="level2 callou-caution" style="color:GoldenRod">
<h2 class="anchored" data-anchor-id="cual-es-la-estructura-fija-me-puedes-decir-cuál-es-la-ecuación-correspondiente">¿Cual es la estructura fija?, me puedes decir cuál es la ecuación correspondiente</h2>
</section>
<p>La estructura aleatoria de los datos, cuando tiene varias fuentes, se representa como una lista de efectos (modelos) en la función <code>lme()</code> de la biblioteca <code>nlme</code>. Otra posibilidad es usar la biblioteca <code>lme4</code> que contiene a la función <code>lmer()</code>. Al respecto, <a href="http://staff.pubhealth.ku.dk/~jufo/courses/rm2018/nlmePackage.pdf">esta lectura puede ser de innterés</a></p>
<p>Este caso, como ya vimos, hay dos cosas en operación:</p>
<ol type="1">
<li>Hay una muestra aleatoria de ratas distintas en cada tratamiento. Cabe esperar un valor promedio de glucógeno distinto para cada animal. Esto lo representaré en el primer componente de la lista.</li>
<li>Hay una muestra aleatoria de fragmentos de hígado tomados de cada rata. Esperamos que estas muestras estimen una misma cantidad de glucógeno para cada animal. Esto lo representaré en el segundo componente de la lista.</li>
</ol>
<p>En el código siguiente tanto el modelo “1” como el “2” son equivalente. Los presento como dos formas de plantear el modelo de efectos aleatorios. Hay que notar que <strong>no es correcto</strong> hacer comparaciones entre modelos que cambian en cuanto al componente “fijo” <strong>si el ajuste se hace mediante el método “REML”</strong>, en caso de tener hipótesis de interés en esta parte del modelo hay que emplear el método “ML”.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>ratas.lme.m1 <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed=</span>glucogeno <span class="sc">~</span> tratamiento <span class="sc">-</span> <span class="dv">1</span>, </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">random=</span><span class="fu">list</span>(<span class="at">rata =</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="at">muestraH=</span> <span class="sc">~</span> <span class="dv">1</span>),</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>ratas_g)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ratas.lme.m1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by REML
  Data: ratas_g 
       AIC      BIC    logLik
  231.6213 240.6003 -109.8106

Random effects:
 Formula: ~1 | rata
        (Intercept)
StdDev:    6.005399

 Formula: ~1 | muestraH %in% rata
        (Intercept) Residual
StdDev:    3.763863 4.600725

Fixed effects:  glucogeno ~ tratamiento - 1 
                 Value Std.Error DF  t-value p-value
tratamientot1 140.5000  4.707166  3 29.84811   1e-04
tratamientot2 151.0000  4.707166  3 32.07875   1e-04
tratamientot3 135.1667  4.707166  3 28.71509   1e-04
 Correlation: 
              trtmn1 trtmn2
tratamientot2 0            
tratamientot3 0      0     

Standardized Within-Group Residuals:
        Min          Q1         Med          Q3         Max 
-1.48211987 -0.47263005  0.03061539  0.42934293  1.82934636 

Number of Observations: 36
Number of Groups: 
              rata muestraH %in% rata 
                 6                 18 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>ratas.lme.m2 <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed =</span> glucogeno <span class="sc">~</span> tratamiento <span class="sc">-</span> <span class="dv">1</span>, </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> rata <span class="sc">/</span> muestraH,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>ratas_g) </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ratas.lme.m2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by REML
  Data: ratas_g 
       AIC      BIC    logLik
  231.6213 240.6003 -109.8106

Random effects:
 Formula: ~1 | rata
        (Intercept)
StdDev:    6.005399

 Formula: ~1 | muestraH %in% rata
        (Intercept) Residual
StdDev:    3.763863 4.600725

Fixed effects:  glucogeno ~ tratamiento - 1 
                 Value Std.Error DF  t-value p-value
tratamientot1 140.5000  4.707166  3 29.84811   1e-04
tratamientot2 151.0000  4.707166  3 32.07875   1e-04
tratamientot3 135.1667  4.707166  3 28.71509   1e-04
 Correlation: 
              trtmn1 trtmn2
tratamientot2 0            
tratamientot3 0      0     

Standardized Within-Group Residuals:
        Min          Q1         Med          Q3         Max 
-1.48211987 -0.47263005  0.03061539  0.42934293  1.82934636 

Number of Observations: 36
Number of Groups: 
              rata muestraH %in% rata 
                 6                 18 </code></pre>
</div>
</div>
<p>Para comparar el efecto del tratamiento hay que usar el método “ML” y ajustar los modelos que contrastan la hipótesis de interés en el componente fijo.</p>
<p>Modelo “nulo” en cuanto a efectos fijos</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ratas_g)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'nmGroupedData', 'groupedData' and 'data.frame':    36 obs. of  4 variables:
 $ glucogeno  : int  131 130 131 125 136 142 150 148 140 143 ...
 $ tratamiento: Factor w/ 3 levels "t1","t2","t3": 1 1 1 1 1 1 1 1 1 1 ...
 $ rata       : Factor w/ 6 levels "r1","r2","r3",..: 1 1 1 1 1 1 2 2 2 2 ...
 $ muestraH   : Factor w/ 3 levels "m1","m2","m3": 1 1 2 2 3 3 1 1 2 2 ...
 - attr(*, "formula")=Class 'formula'  language glucogeno ~ 1 | ordered(rata)/muestraH
  .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
 - attr(*, "formulaList")=List of 2
  ..$ ordered(rata):Class 'formula'  language ~ordered(rata)
  .. .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
  ..$ muestraH     :Class 'formula'  language ~muestraH
  .. .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
 - attr(*, "labels")=List of 2
  ..$ x: chr "rata"
  ..$ y: chr "contenido de glucógeno"
 - attr(*, "order.groups")=List of 2
  ..$ ordered(rata): logi TRUE
  ..$ muestraH     : logi TRUE
 - attr(*, "FUN")=function (x, ...)  </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>ratas.lme.m3 <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed=</span>glucogeno <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>ratas_g, </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">random=</span><span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>rata<span class="sc">/</span>muestraH, <span class="at">method=</span><span class="st">"ML"</span>) </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>ratas.lme.m3</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: ratas_g 
  Log-likelihood: -119.8834
  Fixed: glucogeno ~ 1 
(Intercept) 
   142.2222 

Random effects:
 Formula: ~1 | rata
        (Intercept)
StdDev:    7.561272

 Formula: ~1 | muestraH %in% rata
        (Intercept) Residual
StdDev:    3.763863 4.600725

Number of Observations: 36
Number of Groups: 
              rata muestraH %in% rata 
                 6                 18 </code></pre>
</div>
</div>
<p>Modelo “completo”</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>ratas.lme.m4 <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed=</span>glucogeno <span class="sc">~</span> tratamiento, <span class="at">data=</span>ratas_g, </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">random=</span><span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>rata<span class="sc">/</span>muestraH, <span class="at">method=</span><span class="st">"ML"</span>) </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>ratas.lme.m4</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: ratas_g 
  Log-likelihood: -116.6353
  Fixed: glucogeno ~ tratamiento 
  (Intercept) tratamientot2 tratamientot3 
   140.500000     10.500000     -5.333333 

Random effects:
 Formula: ~1 | rata
        (Intercept)
StdDev:    3.729149

 Formula: ~1 | muestraH %in% rata
        (Intercept) Residual
StdDev:    3.763794 4.600775

Number of Observations: 36
Number of Groups: 
              rata muestraH %in% rata 
                 6                 18 </code></pre>
</div>
</div>
<p>Así podemos comparar el análisis con modelos mixtos y el convencional en cuanto al efecto del tratamiento.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ratas.lme.m4, ratas.lme.m3)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Model df      AIC      BIC    logLik   Test  L.Ratio p-value
ratas.lme.m4     1  6 245.2705 254.7716 -116.6353                        
ratas.lme.m3     2  4 247.7667 254.1008 -119.8834 1 vs 2 6.496197  0.0388</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>ratas.completo.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(glucogeno<span class="sc">~</span>tratamiento<span class="sc">/</span>rata<span class="sc">/</span>muestraH, <span class="at">data=</span>ratas_g)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ratas.completo.lm)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: glucogeno
                          Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
tratamiento                2 1557.56  778.78 36.7927 4.375e-07 ***
tratamiento:rata           3  797.67  265.89 12.5617 0.0001143 ***
tratamiento:rata:muestraH 12  594.00   49.50  2.3386 0.0502907 .  
Residuals                 18  381.00   21.17                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="intervalos-de-confianza" class="level3">
<h3 class="anchored" data-anchor-id="intervalos-de-confianza">Intervalos de confianza</h3>
<p>Es importante contar con intervalos de confianza para describir de mmejor manera los resultados obtenidos. La forma de hacerlo para cada tipo de modelo pude varia, así que ilustraré un par de rutas para obtenerlos.</p>
</section>
<section id="modelo-de-efectos-mixtos-lme" class="level2">
<h2 class="anchored" data-anchor-id="modelo-de-efectos-mixtos-lme">Modelo de efectos mixtos: <code>lme</code></h2>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ratas.lme4.ic <span class="ot">&lt;-</span> <span class="fu">predict</span>(ratas.lme.m4, <span class="at">level =</span> <span class="dv">0</span>, <span class="at">type =</span> <span class="st">"predict"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>ratas.lme4.ic  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ajustado=</span><span class="fu">as.numeric</span>(ratas.lme4.ic), <span class="at">tratamiento=</span>ratas_g<span class="sc">$</span>tratamiento)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intervals</span>(ratas.lme.m4)<span class="sc">$</span>fixed</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   lower       est.      upper
(Intercept)   133.507297 140.500000 147.492703
tratamientot2  -4.479979  10.500000  25.479979
tratamientot3 -20.313312  -5.333333   9.646646
attr(,"label")
[1] "Fixed effects:"</code></pre>
</div>
</div>
<section id="modelo-de-regresión-convencional-lm" class="level4">
<h4 class="anchored" data-anchor-id="modelo-de-regresión-convencional-lm">Modelo de regresión convencional: lm</h4>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>ratas.lm.ic <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">predict</span>(ratas.completo.lm, <span class="at">interval =</span> <span class="st">'confidence'</span>,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">conf.level=</span><span class="fl">0.95</span>, <span class="at">ci.fit=</span><span class="cn">TRUE</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>ratas.lm.ic<span class="sc">$</span>tratamiento <span class="ot">&lt;-</span> ratas_g<span class="sc">$</span>tratamiento</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">min=</span><span class="fu">tapply</span>(ratas.lm.ic<span class="sc">$</span>lwr, ratas.lm.ic<span class="sc">$</span>tratamiento, mean),</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">media=</span><span class="fu">tapply</span>(ratas.lm.ic<span class="sc">$</span>fit, ratas.lm.ic<span class="sc">$</span>tratamiento, mean),</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">max=</span><span class="fu">tapply</span>(ratas.lm.ic<span class="sc">$</span>upr, ratas.lm.ic<span class="sc">$</span>tratamiento, mean))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        min    media      max
t1 133.6653 140.5000 147.3347
t2 144.1653 151.0000 157.8347
t3 128.3319 135.1667 142.0014</code></pre>
</div>
</div>
<p>Bueno, veamos los residuos!!!</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ratas.lme.m4, rata <span class="sc">~</span> <span class="fu">resid</span>(.) <span class="sc">|</span> tratamiento, <span class="at">xlab=</span><span class="st">"residuos"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ratas.lme.m4)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="comparaciones-múltiples" class="level3">
<h3 class="anchored" data-anchor-id="comparaciones-múltiples">Comparaciones múltiples</h3>
<p>Veamos qué está pasando con los efectos de los tratamientos una vez que hemos resuelto con la <em>prueba omnibus</em> que hay algún efecto de tratamiento.</p>
<p>El modelo completo, ¿cambia significativamente al <em>recodifcar</em> los tratamientos de manera que supongamos que el <em>t1</em> no difiere del <em>t2</em>? Esto equivale a comparar los dos mmodelos respectivos.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.4     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::collapse() masks nlme::collapse()
✖ dplyr::filter()   masks stats::filter()
✖ dplyr::lag()      masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>ratas_g<span class="sc">$</span>trat_v1 <span class="ot">&lt;-</span><span class="fu">recode_factor</span>(ratas_g<span class="sc">$</span>tratamiento, <span class="st">"t2"</span><span class="ot">=</span><span class="st">"t1"</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>ratas.lme.m4A <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed=</span>glucogeno <span class="sc">~</span> trat_v1, <span class="at">data=</span>ratas_g, </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">random=</span><span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>rata<span class="sc">/</span>muestraH, <span class="at">method=</span><span class="st">"ML"</span>) </span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>ratas_g<span class="sc">$</span>trat_v2 <span class="ot">&lt;-</span><span class="fu">recode_factor</span>(ratas_g<span class="sc">$</span>tratamiento, <span class="st">"t3"</span><span class="ot">=</span><span class="st">"t2"</span>)</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>ratas.lme.m4B <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed=</span>glucogeno <span class="sc">~</span> trat_v2, <span class="at">data=</span>ratas_g, </span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">random=</span><span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>rata<span class="sc">/</span>muestraH, <span class="at">method=</span><span class="st">"ML"</span>) </span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>ratas_g<span class="sc">$</span>trat_v3 <span class="ot">&lt;-</span><span class="fu">recode_factor</span>(ratas_g<span class="sc">$</span>tratamiento, <span class="st">"t3"</span><span class="ot">=</span><span class="st">"t1"</span>)</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>ratas.lme.m4C <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed=</span>glucogeno <span class="sc">~</span> trat_v3, <span class="at">data=</span>ratas_g, </span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">random=</span><span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>rata<span class="sc">/</span>muestraH, <span class="at">method=</span><span class="st">"ML"</span>) </span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ratas_g)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Grouped Data: glucogeno ~ 1 | ordered(rata)/muestraH
  glucogeno tratamiento rata muestraH trat_v1 trat_v2 trat_v3
1       131          t1   r1       m1      t1      t1      t1
2       130          t1   r1       m1      t1      t1      t1
3       131          t1   r1       m2      t1      t1      t1
4       125          t1   r1       m2      t1      t1      t1
5       136          t1   r1       m3      t1      t1      t1
6       142          t1   r1       m3      t1      t1      t1</code></pre>
</div>
</div>
<p><span style="color:GoldenRod">¿Qué sugieren estos resultados estadísticos?</span></p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ratas.lme.m4A, ratas.lme.m4)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Model df      AIC      BIC    logLik   Test L.Ratio p-value
ratas.lme.m4A     1  5 246.8941 254.8117 -118.4471                       
ratas.lme.m4      2  6 245.2705 254.7716 -116.6353 1 vs 2 3.62358   0.057</code></pre>
</div>
</div>
<p>Preguntémonos lo mismo respecto de los tratamientos <em>t2</em> y <em>t3</em>. Veamos lo que resulta al comparar los modelos</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ratas.lme.m4B, ratas.lme.m4)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Model df      AIC      BIC    logLik   Test  L.Ratio p-value
ratas.lme.m4B     1  5 249.6292 257.5467 -119.8146                        
ratas.lme.m4      2  6 245.2705 254.7716 -116.6353 1 vs 2 6.358622  0.0117</code></pre>
</div>
</div>
<p>Ahora los tratamientos <em>t1</em> y <em>t3</em>. ¿qué resulta al comparar los modelos?</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ratas.lme.m4C, ratas.lme.m4)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Model df      AIC      BIC    logLik   Test  L.Ratio p-value
ratas.lme.m4C     1  5 244.4339 252.3514 -117.2169                        
ratas.lme.m4      2  6 245.2705 254.7716 -116.6353 1 vs 2 1.163313  0.2808</code></pre>
</div>
</div>
<div class="callou-caution" style="color:GoldenRod">
<p>##¿Qué decisión tomarás?</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ratas.lme.m4C)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            numDF denDF  F-value p-value
(Intercept)     1    18 4261.316  &lt;.0001
trat_v3         1     4    8.116  0.0464</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">intervals</span>(ratas.lme.m4)<span class="sc">$</span>fixed</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                   lower       est.      upper
(Intercept)   133.507297 140.500000 147.492703
tratamientot2  -4.479979  10.500000  25.479979
tratamientot3 -20.313312  -5.333333   9.646646
attr(,"label")
[1] "Fixed effects:"</code></pre>
</div>
</div>
</div>
<p>Quizás es más interesante ver los resultados en términos de los valores estimados para cada tratamiento, en lugar de sobre sus diferencias.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">data.frame</span>(<span class="at">trat_1 =</span> <span class="fu">intervals</span>(ratas.lme.m4)<span class="sc">$</span>fixed[<span class="dv">1</span>,],</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">trat_2 =</span> <span class="fu">colSums</span>(<span class="fu">intervals</span>(ratas.lme.m4)<span class="sc">$</span>fixed[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,]),</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">trat_3 =</span> <span class="fu">colSums</span>(<span class="fu">intervals</span>(ratas.lme.m4)<span class="sc">$</span>fixed[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,])))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          lower     est.    upper
trat_1 133.5073 140.5000 147.4927
trat_2 129.0273 151.0000 172.9727
trat_3 108.7140 145.6667 182.6193</code></pre>
</div>
</div>
<p>Si optáramos por tomar al modelo <strong>C</strong> como nuestro modelo mínimo adecuado para describir el experimento de glucógeno, los resultados se verían así:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ratas.lme.m4C)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            numDF denDF  F-value p-value
(Intercept)     1    18 4261.316  &lt;.0001
trat_v3         1     4    8.116  0.0464</code></pre>
</div>
</div>
<p>Este modelo sugiere que es posible argumentar que el tratamiento combinando <strong>t1</strong> y <strong>t3</strong> difiere en forma apreciable o significativa con respecto del <strong>t2</strong>. Esto se aprecia al considerar los valores promedio de los tratamientos, pero no es realmente muy evidente. La forma como estoy calculando los valores tiene que considerar el tipo de reparametrización y la configuración del modelo, no olvides eso.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>nivel_confianza <span class="ot">&lt;-</span> <span class="fl">0.90</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">data.frame</span>(<span class="at">trat_1 =</span> <span class="fu">intervals</span>(ratas.lme.m4, <span class="at">level =</span> nivel_confianza)<span class="sc">$</span>fixed[<span class="dv">1</span>,],</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">trat_2 =</span> <span class="fu">colSums</span>(<span class="fu">intervals</span>(ratas.lme.m4, <span class="at">level =</span> nivel_confianza)<span class="sc">$</span>fixed[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,]),</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trat_3 =</span> <span class="fu">colSums</span>(<span class="fu">intervals</span>(ratas.lme.m4, <span class="at">level =</span> nivel_confianza)<span class="sc">$</span>fixed[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,])))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          lower     est.    upper
trat_1 134.7283 140.5000 146.2717
trat_2 134.1509 151.0000 167.8491
trat_3 117.7401 145.6667 173.5932</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">data.frame</span>(<span class="at">trat_1_y_3 =</span> <span class="fu">intervals</span>(ratas.lme.m4C, <span class="at">level =</span> nivel_confianza)<span class="sc">$</span>fixed[<span class="dv">1</span>,],</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">trat_2 =</span> <span class="fu">colSums</span>(<span class="fu">intervals</span>(ratas.lme.m4C, <span class="at">level =</span> nivel_confianza)<span class="sc">$</span>fixed[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,])))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              lower     est.    upper
trat_1_y_3 133.3366 137.8333 142.3300
trat_2     136.9281 151.0000 165.0719</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="modelo-de-las-manos" class="level1">
<h1>Modelo de las manos</h1>
<p>Hagamos juntos el reanálisis del ejemplo de las manos como un modelo de efectos mixto.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
El modelo puede ser este
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
y_{ijk} = \mu +  L_i + \eta_{j(i)} + \varepsilon_{k(ij)}
\]</span></p>
<ul>
<li>¿Te parece adecuado?</li>
<li>¿Lo puedes explicar?</li>
</ul>
</div>
</div>
<p>En caso de que no tengas los datos de las manos por ahí, te recuerdo como obtenerlos de nuestro repositorio en Google drive.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>url_manos <span class="ot">&lt;-</span> <span class="st">"https://drive.google.com/file/d/1GSQMbbX7szydnIMDkWYDBlFBWqTdkC4k/view?usp=drive_link"</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>dat_manos_id <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(url_manos, <span class="st">"(?&lt;=d/)(.*)(?=/view)"</span>)</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>url_drive <span class="ot">&lt;-</span> <span class="st">"https://docs.google.com/uc?id=%s&amp;export=download"</span> </span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>manos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">sprintf</span>(url_drive, dat_manos_id)) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>